version: '3.8'

services:
  directus:
    image: ghcr.io/maqakh/sudvezi/sudvezi-directus:latest
    container_name: directus
    restart: always
    ports:
      - "8055:8055"
    volumes:
      - ./directus-admin/.env:/directus/env-config:ro
    networks:
      - appnet

  backend:
    image: ghcr.io/maqakh/sudvezi/sudvezi-backend:latest
    container_name: backend
    restart: always
    environment:
      DB_HOST: 193.203.168.142
      DB_PORT: 3306
      DB_DATABASE: u151991570_sudvezi
      DB_USER: u151991570_root
      DB_PASSWORD: Sudvezi123@
    ports:
      - "3000:3000"
    networks:
      - appnet

  frontend:
    image: ghcr.io/maqakh/sudvezi/sudvezi-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://62.171.139.7:3000
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
